# Generated by Django 4.1.3 on 2022-12-12 14:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/djxufsuyv/image/upload/v1670784331/Default-welcomer_orc0jo.png', max_length=255, verbose_name='image'),
        ),
    ]
