# Generated by Django 4.1.3 on 2022-12-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
